if(EXISTS "/mnt/c/Users/Bera/Desktop/ce100-ahmetbera-celik-homeworkproject/build_linux/src/tests/project/project_tests[1]_tests.cmake")
  include("/mnt/c/Users/Bera/Desktop/ce100-ahmetbera-celik-homeworkproject/build_linux/src/tests/project/project_tests[1]_tests.cmake")
else()
  add_test(project_tests_NOT_BUILT project_tests_NOT_BUILT)
endif()
